# Generated by Django 4.0.3 on 2022-03-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
